-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 21:236:232 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smart_data_dispatcher
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart_data_dispatcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_data_dispatcher` DEFAULT CHARACTER SET utf8 ;
USE `smart_data_dispatcher` ;

-- -----------------------------------------------------
-- Table `smart_data_dispatcher`.`environment_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_data_dispatcher`.`environment_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(255) NULL,
  `device_id` VARCHAR(255) NULL,
  `source_id` VARCHAR(255) NULL,
  `device_code` VARCHAR(255) NULL,
  `record_time` VARCHAR(23) NULL,
  `temperature` VARCHAR(23) NULL,
  `humidity` VARCHAR(23) NULL,
  `pm2p5` VARCHAR(23) NULL,
  `pm10` VARCHAR(23) NULL,
  `noise` VARCHAR(23) NULL,
  `wind_speed` VARCHAR(23) NULL,
  `wind_direction` VARCHAR(23) NULL,
  `serial_no` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_data_dispatcher`.`elevator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_data_dispatcher`.`elevator_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(255) NULL,
  `device_id` VARCHAR(255) NULL,
  `source_id` VARCHAR(255) NULL,
  `device_code` VARCHAR(255) NULL,
  `record_time` VARCHAR(23) NULL,
  `start_time` VARCHAR(23) NULL,
  `stop_time` VARCHAR(23) NULL,
  `people_number` VARCHAR(23) NULL,
  `start_height` VARCHAR(23) NULL,
  `stop_height` VARCHAR(23) NULL,
  `speed` VARCHAR(23) NULL,
  `load` VARCHAR(23) NULL,
  `load_percent` VARCHAR(23) NULL,
  `direction` VARCHAR(23) NULL,
  `status` VARCHAR(23) NULL,
  `warning_type` VARCHAR(23) NULL,
  `warning_msg` VARCHAR(235) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_data_dispatcher`.`pak_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_data_dispatcher`.`pak_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(255) NULL,
  `device_id` VARCHAR(255) NULL,
  `source_id` VARCHAR(255) NULL,
  `device_code` VARCHAR(255) NULL,
  `record_time` VARCHAR(23) NULL,
  `card_no` VARCHAR(255) NULL,
  `status` VARCHAR(23) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_data_dispatcher`.`monitor_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_data_dispatcher`.`monitor_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(255) NULL,
  `device_id` VARCHAR(255) NULL,
  `source_id` VARCHAR(255) NULL,
  `device_code` VARCHAR(255) NULL,
  `record_time` VARCHAR(23) NULL,
  `cover_url` VARCHAR(255) NULL,
  `play_url` VARCHAR(255) NULL,
  `cam_no` VARCHAR(5) NULL,
  `status` VARCHAR(23) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
