spring:
  main:
    banner-mode: "console"
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_data_dispatcher?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  profiles:
    active: development

logging:
  config: classpath:logback.xml

server:
  session:
    timeout: 1800
---
#以下是开发版配置
spring:
  profiles: development
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
server:
  port: 10102
my:
  name: "What"
  age: 34

---
#以下是生产版配置
spring:
  profiles: production
  thymeleaf:
    cache: true
server:
  port: 80
my:
  name: "Nandem"
  age: 24
